title: Personal Blog
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: my personal blog to document my own personal projects

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - stem
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
excerpt_separator: "\n//more\n"
